from smart_home_intent_parser import SmartHomeIntentParser
from music_player_intent_parser import MusicPlayerIntentParser
from joke_intent_parser import JokeIntentParser
from weather_intent_parser import WeatherIntentParser